### ISSUE TITLE
Problems with approach

### ISSUE THREAD

**Issue by jayvdb** [AurelienLourot/github-contribs#3]
Using the `created_commits` undocumented API means it does not capture activity unless the user has met the criteria for the commits to appear on their profile.

https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/#commits

This can mean many commits are omitted.

e.g. I suspect that all commits in https://github.com/coala/gh-board will be omitted due to the top set of rules.

Also @Wikimedia committers will have most of their commits omitted because they are done in gerrit and sync'd to GitHub, and they would need to star the relevant repos for those commtis to be included.

Some extra documentation in the README or elsewhere would be appropriate.

Perhaps this tool doesnt want to solve this problem, and that is ok.

**Comment by jayvdb** [comment]
Interesting ... `coala/gh-board` turned up in @li-boxuan 's data, so GitHub's rules are not so clear as they seem.

**Comment by AurelienLourot** [comment]
Wow, thanks a lot @jayvdb for the thorough analysis!

## 1. Criteria for contributions

Actually I'm fine with these criteria, especially:

1.1. we don't want to detect commits to forks, we want to detect real **contributions** (anyone can fork and commit, but the real challenge is to get your work accepted upstream). Although it's debatable and ghuser.io additionally queries forks through the official API to see if some forks happen to be successful (by having stars on their own).

1.2. you have to be either a collaborator or have made pull requests: this is fine as there is no other possible way to get your commits into a repo, right? Either you have push-rights or you make a pull request. The only edge case I see is if you were collaborator but you're **not anymore**. Well and there is of course the case you described in https://github.com/AurelienLourot/ghuser.io/issues/96, which we want to solve differently (commits won't be detected but declared and reviewed).

> Some extra documentation in the README or elsewhere would be appropriate.

Indeed!

## 2. The @wikimedia case

I'll look into it :)

## 3. GraphQL's repositoriesContributedTo

Unfortunately [the documentation](https://developer.github.com/v4/object/user/) says

> `repositoriesContributedTo (RepositoryConnection!)`
> A list of repositories that the user **recently** contributed to.

**Comment by jayvdb** [comment]
The Wikimedia's case isn't so rare.
Most large OSS orgs have the primary Dev not reliant on GitHub, and that
was before the recent change of owner.

Also @weblate edits done via oauth don't involve a PR or repo star so they
are omitted. Quite a few similar tools being created to help non-devs
gitbook is another one.

**Comment by jayvdb** [comment]
Ah, I see https://github.com/AurelienLourot/ghuser.io/issues/22 already sort of covers this for the end-user of ghuser .

**Comment by AurelienLourot** [comment]
I'm looking into the @wikimedia case. I think we're now on the same page: 

Let's take the first commit of [@strayblues's commits on gerrit](https://gerrit.wikimedia.org/r/#/q/author:%22Hagar+Shilo+%253Cstrayblues%2540gmail.com%253E%22+is:merged): `Create 2 OOUI tutorials and an index page`. This was made yesterday and I can see that github is crediting it to @strayblues: https://github.com/wikimedia/oojs-ui/commits?author=strayblues

So the git author/committer isn't the problem here, but as we know this doesn't count as a contribution, so it doesn't show up on her profile: https://github.com/strayblues

And so `github-contribs` can't discover it. I wonder if it would magically pop up on her profile if she starred that repo now. @strayblues do you mind giving a star to https://github.com/wikimedia/oojs-ui ? Thanks a lot!

**Comment by jayvdb** [comment]
@AurelienLourot , it is not a @wikimedia specific case, and you do not need to ping people to ask them to help you see the problem, and I intentionally didnt ping her .  I only used an example so you could see it, and didnt reject it.   It was part of a [training module](https://github.com/BesutKode/sma2017-tugas/blob/master/tasks/translation-2.md#find-10-bugs-in-a-translation-project) I ran, with hundreds of participants.  It is real.  You can do some translations in @weblate to see it for yourself. You need to star or fork repos , per GitHub help pages.

**Comment by AurelienLourot** [comment]
> You need to star or fork repos , per GitHub help pages.

yes but it would have been interesting to know if starring **after** a contribution makes that contribution appear on the profile, or if it was necessary to star **before** the contribution. 

It's easier for strayblues to give a star than for me to search for some translation work to do. We're comparing one single click with hours of work here. I would have appreciated the help. Sorry if I bothered her with my mention. I understand, it won't happen again, I'll take it from here. Thanks for your time and help.

**Comment by jayvdb** [comment]
As mentioned, you can experiment yourself.

But in my experience , starring afterwards does make it appear.  The docs also say that works.

What is less clear is what happens if someone unstars a repo that they have never interacted with except via commits which occurred via oauth or sync's via other means.  Never tried that.

**Comment by AurelienLourot** [comment]
For the record she just starred it (thanks!) and the commit popped up at the author date (July 7th), so for sure if she unstars the repo then the contrib will go away again. 

> The docs also say that works.

Does it? If you search for `star` in the page, there is only one match. I also couldn't find a sentence saying that if you do things afterwards (like starring), "old" contributions would appear on your profile.

**Comment by strayblues** [comment]
Nice to meet you, guys. :)
