### ISSUE TITLE
CLI should save data

### ISSUE THREAD

**Issue by jayvdb** [AurelienLourot/github-contribs#4]
After the CLI was doing such a lot of data fetching/collation/processing, I was expecting it to dump a json file or similar to disk.

A list of repos isnt very rewarding for all that work.

**Comment by AurelienLourot** [comment]
If you run with `--verbose` you see things like
```
2018-08-14 (commits) myself/my-great-repo
2018-08-13 (PRs    ) myorg/other-great-repo
...
```

So you could pipe that output to a text file. Would that be enough or do you need to do more than just grepping?
